- name: "Collecting fsid from the config"
  shell: cat /etc/ceph/ceph.conf | grep fsid | awk '{print$3}'
  register: fsid

- name: "collecting ceph key from the config"
  shell: podman exec -it {{ mon_out.stdout }} ceph auth get-or-create client.openstack | grep -w "key" | awk '{print$3}'
  register: cephkey

- name: "Gather the IP Address from the ceph.conf file"
  shell: cat /etc/ceph/ceph.conf | grep host | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | uniq | paste -s -d, -
  register: monhost

- name: "Generating ceph-ansible-external.yaml file"
  template:
    src: ceph-ansible-external.yaml.j2
    dest: ./template/ceph-ansible-external.yaml
  delegate_to: localhost
